// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/atomic/Accordion.vue')['default']
    Article: typeof import('./src/components/Article.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    PostContent: typeof import('./src/components/PostContent.vue')['default']
    PostInfoBar: typeof import('./src/components/PostInfoBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/sidebar/SidebarItem.vue')['default']
  }
}
